In [5]:
inputs = [1,2,3]
weights = [0.2, 0.8, -0.5]
bias = 2
output=(inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + bias)
print(output)

2.3


In [6]:
# Neuron with 4 inputs
inputs = [1.0, 2.0, 3.0, 2.5]
weights = [0.2, 0.8, -0.5, 0.6]
bias = 2
output=(inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + inputs[3]*weights[3]+ bias)
print(output)

3.8


In [15]:
# Network with 4 inputs and 3 neuron
inputs = [1.0, 2.0, 3.0, 2.5]
weights = [
    [0.2, 0.8, -0.5, 0.6],
    [0.2, -0.8, 0.5, 0.4],
    [0.5, 0.5, -0.1, 2.1],
]

weights1 = weights[0] # List of weights associated with the 1st neuron 
weights2 = weights[1] # List of weights associated with the 2nd neuron
weights3 = weights[2] # List of weights associated with the 3rd neuron

biases = [2, 3, 0.5]
bias1 = biases[0]
bias2 = biases[1]
bias3 = biases[2]

outputs = [
    # Neuron 1:
    inputs[0]*weights1[0]+
    inputs[1]*weights1[1]+
    inputs[2]*weights1[2]+
    inputs[3]*weights1[3]+bias1,
    # Neuron 2:
    inputs[0]*weights2[0]+
    inputs[1]*weights2[1]+
    inputs[2]*weights2[2]+
    inputs[3]*weights2[3]+bias2,
    # Neuron 3:
    inputs[0]*weights3[0]+
    inputs[1]*weights3[1]+
    inputs[2]*weights3[2]+
    inputs[3]*weights3[3]+bias3
]


print(outputs)

[3.8, 4.1, 6.95]


In [17]:
# Inputs and weights
inputs = [1.0, 2.0, 3.0, 2.5]
weights = [
    [0.2, 0.8, -0.5, 0.6],   # Neuron 1
    [0.2, -0.8, 0.5, 0.4],   # Neuron 2
    [0.5, 0.5, -0.1, 2.1],   # Neuron 3
]

# Correct bias alignment
biases = [2, 3, 0.5]   # Neuron 1 → 2, Neuron 2 → 3, Neuron 3 → 0.5

# Manually compute outputs
outputs = [
    # Neuron 1
    inputs[0]*weights[0][0] +
    inputs[1]*weights[0][1] +
    inputs[2]*weights[0][2] +
    inputs[3]*weights[0][3] + biases[0],

    # Neuron 2
    inputs[0]*weights[1][0] +
    inputs[1]*weights[1][1] +
    inputs[2]*weights[1][2] +
    inputs[3]*weights[1][3] + biases[1],

    # Neuron 3
    inputs[0]*weights[2][0] +
    inputs[1]*weights[2][1] +
    inputs[2]*weights[2][2] +
    inputs[3]*weights[2][3] + biases[2],
]

print(outputs)


[3.8, 4.1, 6.95]


In [14]:
# inputs = [1.1, 2.2, 3.3]
# weights = [
#     [2, 0, 0],
#     [2, 2, 0],
#     [2, 2, 2]
# ]
# biases = [0, 1, 1]


In [18]:
# Use loop for the multiplication in a neural network layer

# Input values
inputs = [1.0, 2.0, 3.0, 2.5]

# Weights for each neuron (3 neurons, each with 4 weights)
weights = [
    [0.2, 0.8, -0.5, 0.6],  # Weights for neuron 1
    [0.2, -0.8, 0.5, 0.4],  # Weights for neuron 2
    [0.5, 0.5, -0.1, 2.1],  # Weights for neuron 3
]

# Bias values for each neuron
biases = [2, 3, 0.5]

# Output of the layer (list to store results for each neuron)
layer_output = []

# Iterate over each neuron's weights and corresponding bias
for neuron_weights, neuron_bias in zip(weights, biases):
    # Initialize neuron output to zero
    neuron_output = 0
    
    # Compute weighted sum for the neuron
    for n_input, weight in zip(inputs, neuron_weights):
        # Multiply input by weight and accumulate
        neuron_output += n_input * weight  # W1*X1 + W2*X2 + W3*X3 + W4*X4
    
    # Add the bias term
    neuron_output += neuron_bias
    
    # Append the neuron's output to the layer's output list
    layer_output.append(neuron_output)

# Print the layer output
print(layer_output)

[3.8, 4.1, 6.95]


In [ ]:
# Single neuron using the numpy
import numpy as np
inputs = [1.0, 2.0, 3.0, 2.5]
weights = [0.2, 0.8, -0.5, 0.6]
bias = 2.0
output = np.dot(weights, inputs) + bias
# output = np.dot(inputs, weights) + bias
print(output)

3.8


In [20]:

# Input values
inputs = [1.0, 2.0, 3.0, 2.5]

# Weights for each neuron (3 neurons, each with 4 weights)
weights = [
    [0.2, 0.8, -0.5, 0.6],  # Weights for neuron 1
    [0.2, -0.8, 0.5, 0.4],  # Weights for neuron 2
    [0.5, 0.5, -0.1, 2.1],  # Weights for neuron 3
]

# Bias values for each neuron
biases = [2, 3, 0.5]

# Output of the layer (list to store results for each neuron)
layer_output = np.dot(weights, inputs) + biases

print(layer_output)

[3.8  4.1  6.95]


<div class="alert alert-block alert-danger"> Need to take transpose of weight matrix<div>

In [23]:

# Input values
inputs = [
    [1.0, 2.0, 3.0, -2.5], # Batch 1 inputs (x1, x2, x3)
    [4.0, -7.0, 6.0, 9.5], # Batch 2 inputs (x1, x2, x3)
    [-1.0, 7.0, 3.0, 4.8], # Batch 3 inputs (x1, x2, x3)
]

# Weights for each neuron (3 neurons, each with 4 weights)
weights = [
    [0.2, 0.8, -0.5, 0.6],  # Weights for neuron 1
    [0.2, -0.8, 0.5, 0.4],  # Weights for neuron 2
    [0.5, 0.5, -0.1, 2.1],  # Weights for neuron 3
]

# Bias values for each neuron
biases = [2, 3, 0.5]

# Output of the layer (list to store results for each neuron)
layer_output = np.dot(inputs, (np.array(weights).T)) + biases

print(layer_output)

[[ 0.8   2.1  -3.55]
 [-0.1  16.2  18.35]
 [ 8.78  0.62 13.28]]


In [24]:

# Input values
inputs = np.array([
    [1.0, 2.0, 3.0, -2.5], # Batch 1 inputs (x1, x2, x3)
    [4.0, -7.0, 6.0, 9.5], # Batch 2 inputs (x1, x2, x3)
    [-1.0, 7.0, 3.0, 4.8], # Batch 3 inputs (x1, x2, x3)
])

# Weights for each neuron (3 neurons, each with 4 weights)
weights = np.array([
    [0.2, 0.8, -0.5, 0.6],  # Weights for neuron 1
    [0.2, -0.8, 0.5, 0.4],  # Weights for neuron 2
    [0.5, 0.5, -0.1, 2.1],  # Weights for neuron 3
])

# Bias values for each neuron
biases = np.array([2, 3, 0.5])

# Output of the layer (list to store results for each neuron)
layer_output = np.dot(inputs, weights.T) + biases

print(layer_output)

[[ 0.8   2.1  -3.55]
 [-0.1  16.2  18.35]
 [ 8.78  0.62 13.28]]


In [25]:
# Adding more layers

In [2]:
import numpy as np

# Input values (3 batches, each with 4 features)
inputs = np.array([
    [1.0, 2.0, 3.0, -2.5],
    [4.0, -7.0, 6.0, 9.5],
    [-1.0, 7.0, 3.0, 4.8],
])

# Weights for layer 1 (4 neurons, each with 4 weights)
weights1 = np.array([
    [0.2, 0.8, -0.5, 0.6],
    [0.2, -0.8, 0.5, 0.4],
    [0.5, 0.5, -0.1, 2.1],
    [0.1, 0.3, -0.2, 0.9],  # Added 4th neuron
])

# Biases for layer 1 (4 biases for 4 neurons)
biases1 = np.array([2, 3, 0.5, 1])  # Added bias for 4th neuron

# Weights for layer 2 (3 neurons, each with 4 weights)
weights2 = np.array([
    [0.1, 0.5, -0.3, 0.7],
    [0.3, -0.9, 0.6, 0.2],
    [0.4, 0.6, -0.2, 1.8],
])

# Biases for layer 2 (3 biases for 3 neurons)
biases2 = np.array([1, 2, 0.8])

# Compute layer 1 output
layer1_output = np.dot(inputs, weights1.T) + biases1

# Compute layer 2 output
layer2_output = np.dot(layer1_output, weights2.T) + biases2

# Print the layer 2 output
print(layer2_output)

[[ 2.39  -2.01   1.02 ]
 [ 8.24  -0.27  18.78 ]
 [ 2.908 13.388 14.124]]


In [3]:
import numpy as np

# Input values (3 batches, each with 4 features)
inputs = np.array([
    [1.0, 2.0, 3.0, -2.5],  # Batch 1
    [4.0, -7.0, 6.0, 9.5],  # Batch 2
    [-1.0, 7.0, 3.0, 4.8],  # Batch 3
])

# Weights and biases for Layer 1 (4 neurons, 4 inputs each)
weights1 = np.array([
    [0.2, 0.8, -0.5, 0.6],
    [0.2, -0.8, 0.5, 0.4],
    [0.5, 0.5, -0.1, 2.1],
    [0.1, 0.3, -0.2, 0.9],
])
biases1 = np.array([2, 3, 0.5, 1])

# Weights and biases for Layer 2 (5 neurons, 4 inputs each)
weights2 = np.array([
    [0.1, 0.5, -0.3, 0.7],
    [0.3, -0.9, 0.6, 0.2],
    [0.4, 0.6, -0.2, 1.8],
    [0.2, 0.4, -0.1, 0.5],
    [0.6, -0.3, 0.8, -0.4],
])
biases2 = np.array([1, 2, 0.8, 1.5, 0.3])

# Weights and biases for Layer 3 (3 neurons, 5 inputs each)
weights3 = np.array([
    [0.4, -0.2, 0.7, 0.1, 0.9],
    [0.3, 0.6, -0.5, 0.2, 0.4],
    [0.1, 0.8, 0.3, -0.6, 0.5],
])
biases3 = np.array([0.7, 1.2, 0.4])

# Weights and biases for Layer 4 (2 neurons, 3 inputs each)
weights4 = np.array([
    [0.5, -0.3, 0.2],
    [0.1, 0.7, -0.4],
])
biases4 = np.array([0.9, 0.6])

# Compute Layer 1 output
layer1_output = np.dot(inputs, weights1.T) + biases1

# Compute Layer 2 output
layer2_output = np.dot(layer1_output, weights2.T) + biases2

# Compute Layer 3 output
layer3_output = np.dot(layer2_output, weights3.T) + biases3

# Compute Layer 4 output
layer4_output = np.dot(layer3_output, weights4.T) + biases4

# Print the final output
print("Layer 4 Output:")
print(layer4_output)

Layer 4 Output:
[[ 0.8378   1.7932 ]
 [14.5439   0.4903 ]
 [12.65798  1.80522]]
