In [1]:
import numpy as np

In [2]:
A = [[1,2,3],
     [4,5,6],
     [7,8,9]]


In [4]:
np.sum(A)

np.int64(45)

In [5]:
np.sum(A, axis=None)

np.int64(45)

In [6]:
np.sum(A, axis=0)

array([12, 15, 18])

In [7]:
np.sum(A, axis=1)

array([ 6, 15, 24])

In [9]:
# TRY EXERCISE

A = [[1,2,3],[4,5,6],[7,8,9]]

print(np.sum(A))

print(np.sum(A, axis=0))
print(np.sum(A, axis=0).shape)

print(np.sum(A, axis=1))
print(np.sum(A, axis=1).shape)

print(np.sum(A, axis=0, keepdims=True))
print(np.sum(A, axis=0, keepdims=True).shape)

print(np.sum(A, axis=1, keepdims=True))
print(np.sum(A, axis=1, keepdims=True).shape)

print(np.max(A, axis=0))
print(np.max(A, axis=1))

45
[12 15 18]
(3,)
[ 6 15 24]
(3,)
[[12 15 18]]
(1, 3)
[[ 6]
 [15]
 [24]]
(3, 1)
[7 8 9]
[3 6 9]


In [12]:
# Broadcasting 

A = [[1,2,3],[4,5,6],[7,8,9]]

B = [[1,2,3]]

In [13]:
A+B

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3]]

In [14]:
A-np.max(A, axis=1)

array([[-2, -4, -6],
       [ 1, -1, -3],
       [ 4,  2,  0]])

In [15]:
A-np.max(A,axis=1, keepdims=True)

array([[-2, -1,  0],
       [-2, -1,  0],
       [-2, -1,  0]])