In [1]:
import numpy as np

In [ ]:
# Initial parameters
weights = np.array([-3.0,-1.0,2.0])
bias = 1.0
inputs = np.array([1.0, -2.0, 3.0])
target_output=0.0
learning_rate=0.001

def relu(x):
    return np.maximum(0, x)

def relu_derivative(x):
    return np.where(x>0, 1.0, 0.0)

for iteration in range(100):
    # forward pass
    linear_output = np.dot(weights, inputs) + bias
    output = relu(linear_output)
    loss=(output-target_output)**2

    # backword pass
    dloss_doutput = 2*(output-target_output)
    doutput_dlinear = relu_derivative(linear_output)
    dlinear_dweights = inputs
    dlinear_dbias = 1.0


    dloss_dlinear = dloss_doutput*doutput_dlinear
    dloss_dweigths = dloss_dlinear*dlinear_dweights
    dloss_dbias =  dloss_dlinear*dlinear_dbias

    # update weights and biases 
    weights -= learning_rate*dloss_dweigths
    bias -= learning_rate*dloss_dbias

    # pritn loss for iteration
    print(f"Iteration {iteration+1}, Loss {loss}")

print(f"final weights {weights}")
print(f"final bias {bias}")

Iteration 1, Loss 36.0
Iteration 2, Loss 33.872399999999985
Iteration 3, Loss 31.870541159999995
Iteration 4, Loss 29.98699217744401
Iteration 5, Loss 28.21476093975706
Iteration 6, Loss 26.54726856821742
Iteration 7, Loss 24.978324995835766
Iteration 8, Loss 23.502105988581878
Iteration 9, Loss 22.113131524656684
Iteration 10, Loss 20.80624545154949
Iteration 11, Loss 19.576596345362915
Iteration 12, Loss 18.419619501351963
Iteration 13, Loss 17.331019988822064
Iteration 14, Loss 16.306756707482677
Iteration 15, Loss 15.343027386070442
Iteration 16, Loss 14.43625446755368
Iteration 17, Loss 13.583071828521266
Iteration 18, Loss 12.780312283455652
Iteration 19, Loss 12.024995827503426
Iteration 20, Loss 11.314318574097976
Iteration 21, Loss 10.645642346368787
Iteration 22, Loss 10.016484883698395
Iteration 23, Loss 9.424510627071816
Iteration 24, Loss 8.867522049011871
Iteration 25, Loss 8.34345149591527
Iteration 26, Loss 7.850353512506679
Iteration 27, Loss 7.386397619917536
Iteratio

In [9]:
import numpy as np

# Initial parameters
initial_weights = np.array([-3.0, -1.0, 2.0])  # Weight values for inputs x0, x1, x2
initial_bias = 1.0  # Bias term
input_values = np.array([1.0, -2.0, 3.0])  # Input values x0, x1, x2
target_value = 0.0  # Desired output value
learning_rate = 0.001  # Step size for weight updates

# Activation function: Returns max(0, x) to introduce non-linearity
def relu(activation_input):
    return np.maximum(0, activation_input)

# Derivative of ReLU: 1 if input > 0, 0 otherwise
def relu_derivative(activation_input):
    return np.where(activation_input > 0, 1.0, 0.0)

# Training loop for 100 iterations
for iteration in range(100):
    # Forward pass: Compute the prediction
    # Calculate the weighted sum of inputs plus bias
    weighted_sum = np.dot(initial_weights, input_values) + initial_bias
    # Apply ReLU activation to get the output
    predicted_output = relu(weighted_sum)
    # Compute the loss (mean squared error)
    loss = (predicted_output - target_value) ** 2

    # Backward pass: Compute gradients
    # Gradient of loss with respect to output: 2 * (output - target)
    gradient_loss_output = 2 * (predicted_output - target_value)
    # Gradient of output with respect to weighted sum (ReLU derivative)
    gradient_output_weighted_sum = relu_derivative(weighted_sum)
    # Gradient of weighted sum with respect to weights (equals inputs)
    gradient_weighted_sum_weights = input_values
    # Gradient of weighted sum with respect to bias (always 1)
    gradient_weighted_sum_bias = 1.0

    # Combine gradients using chain rule
    # Gradient of loss with respect to weighted sum
    gradient_loss_weighted_sum = gradient_loss_output * gradient_output_weighted_sum
    # Gradient of loss with respect to weights
    gradient_loss_weights = gradient_loss_weighted_sum * gradient_weighted_sum_weights
    # Gradient of loss with respect to bias
    gradient_loss_bias = gradient_loss_weighted_sum * gradient_weighted_sum_bias

    # Update weights and bias using gradient descent
    initial_weights -= learning_rate * gradient_loss_weights
    initial_bias -= learning_rate * gradient_loss_bias

    # Print loss for each iteration to track progress
    print(f"Iteration {iteration + 1}, Loss: {loss}")

# Print final trained parameters
print(f"Final weights: {initial_weights}")
print(f"Final bias: {initial_bias}")

Iteration 1, Loss: 36.0
Iteration 2, Loss: 33.872399999999985
Iteration 3, Loss: 31.870541159999995
Iteration 4, Loss: 29.98699217744401
Iteration 5, Loss: 28.21476093975706
Iteration 6, Loss: 26.54726856821742
Iteration 7, Loss: 24.978324995835766
Iteration 8, Loss: 23.502105988581878
Iteration 9, Loss: 22.113131524656684
Iteration 10, Loss: 20.80624545154949
Iteration 11, Loss: 19.576596345362915
Iteration 12, Loss: 18.419619501351963
Iteration 13, Loss: 17.331019988822064
Iteration 14, Loss: 16.306756707482677
Iteration 15, Loss: 15.343027386070442
Iteration 16, Loss: 14.43625446755368
Iteration 17, Loss: 13.583071828521266
Iteration 18, Loss: 12.780312283455652
Iteration 19, Loss: 12.024995827503426
Iteration 20, Loss: 11.314318574097976
Iteration 21, Loss: 10.645642346368787
Iteration 22, Loss: 10.016484883698395
Iteration 23, Loss: 9.424510627071816
Iteration 24, Loss: 8.867522049011871
Iteration 25, Loss: 8.34345149591527
Iteration 26, Loss: 7.850353512506679
Iteration 27, Loss:

<div class="alert alert-block alert-danger">Backpropagation: Through Entire Layer(Multiple Neurons)<div>

In [4]:
import numpy as np

# --- Initialization ---
# Input vector
inputs = np.array([1, 2, 3, 4])

# Weight matrix (3 neurons, 4 inputs each)
weights = np.array([
    [0.1, 0.2, 0.3, 0.4],
    [0.5, 0.6, 0.7, 0.8],
    [0.9, 1.0, 1.1, 1.2]
])

# Bias vector (one bias per neuron)
biases = np.array([0.1, 0.2, 0.3])

# Learning rate
learning_rate = 0.001

# --- Activation Functions ---
def relu(x):
    """Apply ReLU activation: f(x) = max(0, x)"""
    return np.maximum(0, x)

def relu_derivative(x):
    """Compute ReLU derivative: 1 if x > 0, else 0"""
    return np.where(x > 0, 1.0, 0.0)

# --- Training Loop ---
for iteration in range(60):
    # Step 1: Forward Pass
    # Compute weighted sum: z = Wx + b
    z = np.dot(weights, inputs) + biases
    
    # Apply ReLU activation
    a = relu(z)
    
    # Compute output: y = sum of activations
    y = np.sum(a)
    
    # Compute loss: L = y^2 (simple loss for demonstration)
    loss = y**2
    
    # Step 2: Backward Pass
    # Gradient of loss w.r.t. output: dL/dy = 2y
    dL_dy = 2 * y
    
    # Gradient of output w.r.t. activations: dy/da = [1, 1, 1]
    dy_da = np.ones_like(a)
    
    # Gradient of loss w.r.t. activations: dL/da = dL/dy * dy/da
    dL_da = dL_dy * dy_da
    
    # Gradient of activations w.r.t. pre-activations: da/dz = ReLU'(z)
    da_dz = relu_derivative(z)
    
    # Gradient of loss w.r.t. pre-activations: dL/dz = dL/da * da/dz
    dL_dz = dL_da * da_dz
    
    # Gradient of loss w.r.t. weights: dL/dW = dL/dz * x^T
    dL_dW = np.outer(dL_dz, inputs)
    
    # Gradient of loss w.r.t. biases: dL/db = dL/dz
    dL_db = dL_dz
    
    # Step 3: Update Parameters
    # Update weights: W = W - learning_rate * dL/dW
    weights -= learning_rate * dL_dW
    
    # Update biases: b = b - learning_rate * dL/db
    biases -= learning_rate * dL_db
    
    # Step 4: Log Progress
    if iteration % 5 == 0:
        print(f"Iteration {iteration + 1}, Loss: {loss:.3f}")

# --- Final Results ---
print("\nFinal weights:")
print(weights)
print("\nFinal biases:")
print(biases)

Iteration 1, Loss: 466.560
Iteration 6, Loss: 82.923
Iteration 11, Loss: 22.066
Iteration 16, Loss: 10.108
Iteration 21, Loss: 5.330
Iteration 26, Loss: 2.810
Iteration 31, Loss: 1.482
Iteration 36, Loss: 0.781
Iteration 41, Loss: 0.412
Iteration 46, Loss: 0.217
Iteration 51, Loss: 0.115
Iteration 56, Loss: 0.060

Final weights:
[[-0.00698895 -0.01397789 -0.02096684 -0.02795579]
 [ 0.25975286  0.11950572 -0.02074143 -0.16098857]
 [ 0.54123958  0.28247916  0.02371875 -0.23504167]]

Final biases:
[-0.00698895 -0.04024714 -0.05876042]
